task:
  name: CI success
  container: {image: "busybox"}
  depends_on:
    - Lint
    - Test

Lint_task:
  container:
    image: debian:13-slim
  install_script:
    - apt-get update
    - apt-get install -y make clang-tools git
  script:
    - make lint

Test_task:
  depends_on:
    - Lint
  container:
    image: debian:13-slim
  install_script:
    - apt-get update
    - apt-get install -y build-essential clang clang-tools git
  script:
    - make test
